/* cSpell:disable */

import { Em, makePerson } from '@commands/seed/helpers';

export const seedPeople = (em: Em) => {
  const p = makePerson(em);
  return {
    unknown: p({
      firstName: 'Unknown',
      lastName: 'Unknown',
      pseudonym: 'Unknown',
    }),
    alEwing: p({ firstName: 'Al', lastName: 'Ewing' }),
    pacoMedina: p({ firstName: 'Paco', lastName: 'Medina' }),
    carlosGomez: p({ firstName: 'Carlos', lastName: 'Gomez' }),
    jordanMorris: p({ firstName: 'Jordan', lastName: 'Morris' }),
    lukeRoss: p({ firstName: 'Luke', lastName: 'Ross' }),
    ramonRosanas: p({ firstName: 'Ramon', lastName: 'Rosanas' }),
    frankMartin: p({ firstName: 'Frank', lastName: 'Martin' }),
    stefanoCaselli: p({ firstName: 'Stefano', lastName: 'Caselli' }),
    federicoBlee: p({ firstName: 'Federico', lastName: 'Blee' }),
    giuseppeCamuncoli: p({ firstName: 'Giuseppe', lastName: 'Camuncoli' }),
    charlesSoule: p({ firstName: 'Charles', lastName: 'Soule' }),
    javierPina: p({ firstName: 'Javier', lastName: 'Pina' }),
    ryanStegman: p({ firstName: 'Ryan', lastName: 'Stegman' }),
    adamKubert: p({ firstName: 'Adam', lastName: 'Kubert' }),
    joeKelly: p({ firstName: 'Joe', lastName: 'Kelly' }),
    francescoManna: p({ firstName: 'Francesco', lastName: 'Manna' }),
    edMcguinness: p({ firstName: 'Ed', lastName: 'McGuinness' }),
    marteGracia: p({ firstName: 'Marte', lastName: 'Gracia' }),
    frankDArmata: p({ firstName: 'Frank', lastName: "D'Armata" }),
    alexSinclair: p({ firstName: 'Alex', lastName: 'Sinclair' }),
    lauraMartin: p({ firstName: 'Laura', lastName: 'Martin' }),
    erikLarsen: p({ firstName: 'Erik', lastName: 'Larsen' }),
    denizCamp: p({ firstName: 'Deniz', lastName: 'Camp' }),
    alexPaknadel: p({ firstName: 'Alex', lastName: 'Paknadel' }),
    patrickBoutin: p({ firstName: 'Patrick', lastName: 'Boutin' }),
    philNoto: p({ firstName: 'Phil', lastName: 'Noto' }),
    leeFerguson: p({ firstName: 'Lee', lastName: 'Ferguson' }),
    javierPulido: p({ firstName: 'Javier', lastName: 'Pulido' }),
    terryDodson: p({ firstName: 'Terry', lastName: 'Dodson' }),
    rachelDodson: p({ firstName: 'Rachel', lastName: 'Dodson' }),
    jonasScharf: p({ firstName: 'Jonas', lastName: 'Scharf' }),
    cafu: p({ pseudonym: 'Cafu' }),
    markBrooks: p({ firstName: 'Mark', lastName: 'Brooks' }),
    brianMichaelBendis: p({ firstName: 'Brian Michael', lastName: 'Bendis' }),
    markBagley: p({ firstName: 'Mark', lastName: 'Bagley' }),
    richardIsanove: p({ firstName: 'Richard', lastName: 'Isanove' }),
    chipZdarsky: p({ firstName: 'Chip', lastName: 'Zdarsky' }),
    frankAlpizar: p({ firstName: 'Frank', lastName: 'Alpizar' }),
    delioDiaz: p({ firstName: 'Delio', lastName: 'Diaz' }),
    jedMacKay: p({ firstName: 'Jed', lastName: 'MacKay' }),
    federicoVicentini: p({ firstName: 'Federico', lastName: 'Vicentini' }),
    ryanNorth: p({ firstName: 'Ryan', lastName: 'North' }),
    francescoMobili: p({ firstName: 'Francesco', lastName: 'Mobili' }),
    arthurHesli: p({ firstName: 'Arthur', lastName: 'Hesli' }),
    jonathanHickman: p({ firstName: 'Jonathan', lastName: 'Hickman' }),
    dustinWeaver: p({ firstName: 'Dustin', lastName: 'Weaver' }),
    geraldParel: p({ firstName: 'Gerald', lastName: 'Parel' }),
    codyZiglar: p({ firstName: 'Cody', lastName: 'Ziglar' }),
    johnRomitaJr: p({
      firstName: 'John',
      lastName: 'Romita',
      pseudonym: 'John Romita Jr.',
    }),
    patrickGleason: p({ firstName: 'Patrick', lastName: 'Gleason' }),
    deanWhite: p({ firstName: 'Dean', lastName: 'White' }),
    stuartImmonen: p({ firstName: 'Stuart', lastName: 'Immonen' }),
    edBrubaker: p({ firstName: 'Ed', lastName: 'Brubaker' }),
    zacThompson: p({ firstName: 'Zac', lastName: 'Thompson' }),
    dioNeves: p({ firstName: 'Dio', lastName: 'Neves' }),
    philipTan: p({ firstName: 'Philip', lastName: 'Tan' }),
    jayDavidRamos: p({ firstName: 'Jay David', lastName: 'Ramos' }),
    jesusSaiz: p({ firstName: 'Jesus', lastName: 'Saiz' }),
    ronGarney: p({ firstName: 'Ron', lastName: 'Garney' }),
    markWaid: p({ firstName: 'Mark', lastName: 'Waid' }),
    markoDjurdjevic: p({ firstName: 'Marko', lastName: 'Djurdjevic' }),
    mikeDeodatoJr: p({
      firstName: 'Mike',
      lastName: 'Deodato',
      pseudonym: 'Mike Deodato Jr.',
    }),
    alexSchomburg: p({ firstName: 'Alex', lastName: 'Schomburg' }),
    rainBeredo: p({ firstName: 'Rain', lastName: 'Beredo' }),
    davidAja: p({ firstName: 'David', lastName: 'Aja' }),
    stefanoGaudiano: p({ firstName: 'Stefano', lastName: 'Gaudiano' }),
    michaelLark: p({ firstName: 'Michael', lastName: 'Lark' }),
    robertoDelatorre: p({ firstName: 'Roberto', lastName: 'Delatorre' }),
    scottGeorgeEaton: p({ firstName: 'Scott George', lastName: 'Eaton' }),
  };
};

export type People = ReturnType<typeof seedPeople>;
